# Generated by Django 5.2.15 on 2026-07-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='cycle',
            field=models.CharField(blank=True, choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'College'), ('LYCEE', 'Lycee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='identifiant_unique',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='academie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='factures.academie'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='factures.commune'),
        ),
        migrations.CreateModel(
            name='DirectionProvinciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('academie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_provinciales', to='factures.academie')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='direction_provinciale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='factures.directionprovinciale'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='direction_provinciale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='factures.directionprovinciale'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('nom', 'direction_provinciale')},
        ),
    ]
