# Generated by Django 5.2.15 on 2026-07-09 11:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_academie_commune_etablissement_actif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academie',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='directionprovinciale',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission', '-date_creation']},
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compteur', models.CharField(choices=[('EAU', 'Eau'), ('ELECTRICITE', 'Electricite')], max_length=20)),
                ('numero_contrat', models.CharField(max_length=100, unique=True)),
                ('code_compteur', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='factures.etablissement')),
            ],
            options={
                'ordering': ['etablissement__nom', 'type_compteur', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='compteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='factures.compteur'),
        ),
        migrations.CreateModel(
            name='SaisieConsommationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('ancien_index', models.PositiveIntegerField()),
                ('nouvel_index', models.PositiveIntegerField()),
                ('quantite_consommee', models.PositiveIntegerField(default=0, editable=False)),
                ('tarif_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('montant_fournisseur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ecart_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('taux_ecart', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6)),
                ('statut_saisie', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE_ETABLISSEMENT', "Validee par l'etablissement"), ('CONTROLEE_DP', 'Controlee par la DP'), ('CONTROLEE_ACADEMIE', "Controlee par l'academie")], default='BROUILLON', max_length=30)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisies_consommation', to='factures.compteur')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisies_consommation', to='factures.etablissement')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies_consommation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-annee', '-mois', '-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='AlerteConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_alerte', models.CharField(choices=[('INFO', 'Info'), ('SURVEILLANCE', 'Surveillance'), ('CRITIQUE', 'Critique')], max_length=20)),
                ('type_alerte', models.CharField(choices=[('ECART_FACTURATION', 'Ecart de facturation'), ('ABSENCE_SAISIE', 'Absence de saisie'), ('INDEX_INCOHERENT', 'Index incoherent')], max_length=30)),
                ('message', models.TextField()),
                ('traitee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('academie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes_consommation', to='factures.academie')),
                ('direction_provinciale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes_consommation', to='factures.directionprovinciale')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_consommation', to='factures.etablissement')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
                ('compteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes_consommation', to='factures.compteur')),
                ('saisie_consommation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='factures.saisieconsommationmensuelle')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='compteur',
            constraint=models.UniqueConstraint(fields=('etablissement', 'type_compteur', 'code_compteur'), name='unique_compteur_par_etablissement_type_code'),
        ),
        migrations.AddConstraint(
            model_name='saisieconsommationmensuelle',
            constraint=models.UniqueConstraint(fields=('compteur', 'annee', 'mois'), name='unique_saisie_mensuelle_par_compteur'),
        ),
    ]
