# Generated by Django 5.2.15 on 2026-06-27 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('kilometrage', models.IntegerField(default=0)),
                ('affectation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factures.etablissement')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsommationCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite_litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.vehicule')),
            ],
        ),
    ]
