# Generated by Django 5.2.15 on 2026-06-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Général'), ('RESP_FIN', 'Responsable Financier'), ('RESP_INFO', 'Responsable Parc Informatique'), ('RESP_AUTO', 'Responsable Parc Automobile')], default='RESP_FIN', max_length=20),
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('modele_modifie', models.CharField(max_length=100)),
                ('id_objet', models.IntegerField(blank=True, null=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
