# Generated by Django 5.2.15 on 2026-07-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_logactivite'),
        ('factures', '0002_academie_commune_etablissement_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='factures.academie'),
        ),
        migrations.AddField(
            model_name='user',
            name='direction_provinciale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='factures.directionprovinciale'),
        ),
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='factures.etablissement'),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_acces',
            field=models.CharField(choices=[('ACADEMIE', 'Academie'), ('DP', 'Direction Provinciale'), ('ETABLISSEMENT', 'Etablissement')], default='ACADEMIE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Général'), ('RESP_FIN', 'Responsable Financier'), ('RESP_INFO', 'Responsable Parc Informatique'), ('RESP_AUTO', 'Responsable Parc Automobile'), ('DP_RESP_FIN', 'Responsable Financier DP'), ('DP_RESP_INFO', 'Responsable Parc Informatique DP'), ('DP_RESP_AUTO', 'Responsable Parc Automobile DP'), ('ETAB_RESP_CONSO', 'Responsable Consommation Etablissement')], default='RESP_FIN', max_length=20),
        ),
    ]
