# Generated by Django 5.2.15 on 2026-07-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_academie_user_direction_provinciale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
