# Generated by Django 5.2.15 on 2026-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementinformatique',
            name='designation',
            field=models.CharField(choices=[('ECRAN', 'Écran'), ('UNITE_CENTRALE', 'Unité centrale'), ('CLAVIER', 'Clavier'), ('SOURIS', 'Souris'), ('IMPRIMANTE', 'Imprimante'), ('SCANNER', 'Scanner'), ('ONDULEUR', 'Onduleur'), ('DISQUE_DUR', 'Disque dur externe'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Désignation'),
        ),
    ]
